#!/bin/bash

echo "========================================"
echo "Ontology 数据完整性检查"
echo "========================================"
echo ""

echo "1. API 端点检查..."
echo "   Object Types: $(curl -s http://localhost:8000/api/ontologies/ai-compass/objectTypes | jq '.data | length')"
echo "   Link Types: $(curl -s http://localhost:8000/api/ontologies/ai-compass/linkTypes | jq '.data | length')"
echo "   Value Types: $(curl -s http://localhost:8000/api/ontologies/ai-compass/valueTypes | jq '.data | length')"
echo "   Action Types: $(curl -s http://localhost:8000/api/ontologies/ai-compass/actionTypes | jq '.data | length')"
echo "   Functions: $(curl -s http://localhost:8000/api/ontologies/ai-compass/functions | jq '.data | length')"
echo "   Interfaces: $(curl -s http://localhost:8000/api/ontologies/ai-compass/interfaces | jq '.data | length')"
echo ""
echo "2. Objects 检查..."
echo "   Tools: $(curl -s 'http://localhost:8000/api/ontologies/ai-compass/objectTypes/AIGCTool/objects?limit=1' | jq '.total')"
echo "   Categories: $(curl -s 'http://localhost:8000/api/ontologies/ai-compass/objectTypes/ToolCategory/objects?limit=1' | jq '.total')"
echo "   Providers: $(curl -s 'http://localhost:8000/api/ontologies/ai-compass/objectTypes/ToolProvider/objects?limit=1' | jq '.total')"
echo ""
echo "3. 排名/热度数据..."
echo "   Heat Snapshots: $(curl -s http://localhost:8000/api/aigc/heat/hot?limit=1 | jq '.hotTools | length') tools"
echo "   Rankings: $(curl -s http://localhost:8000/api/aigc/rankings/composite | jq '.data.rankings | length') items"
echo ""
echo "========================================"
echo "前端页面检查..."
echo "========================================"
echo "   Homepage: http://localhost:3000"
echo "   Models: http://localhost:3000/models"
echo "   Rankings: http://localhost:3000/rankings"
echo "   Categories: http://localhost:3000/categories"
echo "   Ontologies: http://localhost:3000/ontologies"
echo "========================================"
